### ISSUE TITLE
Armorcore doesn't print exceptions to the console

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorcore#13]
When an exception occurs (e.g. in Iron because a resource couldn't be loaded), Krom just crashes without any information about what's happening. Currently the only way to find out is to build the application for another target like html5 to get the error message.

Using the latest kromx binaries for Armory on Windows 10.

**Comment by luboslenco** [comment]
There should be a `stderr.txt` file placed alongside the Krom binary containing the stacktrace. For dev purposes it is probably better to run armorcore directly from Visual Studio, with command line arguments set to the location of `krom.js` file.

**Comment by MoritzBrueckner** [comment]
Unfortunately not, there is just a small dump file (`kinc.dmp`). There is also no `stderr.txt` along the compiled krom output files. 
Running Krom from Visual Studio just to debug some Armory scripts sounds a bit tedious to me, is there no other way? If I remember correctly error messages were just printed to the console not too long ago.

**Comment by luboslenco** [comment]
Are you not getting the JS stack traces printed to the console at all? It seems to work as usual here. However if Krom crashes that indicates a problem somewhere in the C code for Kinc or Krom bindings.

```
__________  [Armory] Compiling  __________
Exporting Scene
Scene exported in 0.010879278182983398
Finished in 3.8569459915161133
Falling back to the system's preferred WASAPI mix format.
Trace: TypeError: Cannot set property 'c' of undefined
    at arm_MyTrait.init (<anonymous>:384:9)
    at iron_App.render (<anonymous>:1962:5)
    at Function.kha_System.render (<anonymous>:21949:3)
    at kha_SystemImpl.renderCallback (<anonymous>:22090:13)
```

**Comment by MoritzBrueckner** [comment]
Ah, so the problem isn't related to error logging in general. I tested it with an error like you forced and indeed there is an error message in the console and Krom keeps running.

The crashes happen when a resource can't be loaded in Iron (= when the typical `cannot read hxBytes of undefined` error occurs).

**Comment by MoritzBrueckner** [comment]
Sorry for bothering you again, is there any news on this? When some kind of resource in Iron can't be loaded, Krom crashes and you'll have to export to html5 in order to see the error message.

**Comment by luboslenco** [comment]
I still get the `cannot read hxBytes of undefined` message when blob load fails, but managed to reproduce and fix the missing image crash in latest armsdk now.

**Comment by MoritzBrueckner** [comment]
Thank you very much! 👍
