### ISSUE TITLE
Crash on custom exceptions

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorcore#15]
Throwing custom exceptions leads to a crash in Armorcore, making it impossible to see what's wrong on that target:

```haxe
throw "This will crash armorcore";
```

Windows 10
Using latest Krom submodule from Armory

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorcore/commit/4795862a96832378e370e999c379672843eaf37d, thanks for report. Binary update soon.
