### ISSUE TITLE
Crash when locking image with RGBA128 format

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorcore#17]
Minimal example:
```haxe
var img = kha.Image.create(16, 1, TextureFormat.RGBA128, Usage.StaticUsage);
img.lock();
```

When using other formats such as `RGBA64`, no crash occurs. Visual Studio breaks [in this line](
https://github.com/armory3d/armorcore/blob/01eb9e4f2605c9efd43e6acd2f80e7b959874cdf/Sources/main.cpp#L2039), however I think the actual error occurs [in the line above](https://github.com/armory3d/armorcore/blob/01eb9e4f2605c9efd43e6acd2f80e7b959874cdf/Sources/main.cpp#L2038) as it is shown in the stack trace:

![Stack trace](https://user-images.githubusercontent.com/17685000/111033767-267e7980-8413-11eb-8522-cbac26471252.png)

The error message itself is not very helpful:

```
#
# Fatal error in , line 0
# ignored
#
#
#
#FailureMessage Object: 000000834F1EDF40Krom.exe hat einen Haltepunkt ausgelöst.
```

This issue looks similar to https://github.com/armory3d/armorcore/issues/6 but there is no way to set a `readable` attribute when creating a new image.

Using latest armorcore from the master branch (https://github.com/armory3d/armorcore/commit/01eb9e4f2605c9efd43e6acd2f80e7b959874cdf) on Windows 10.

**Edit**: `kinc_g4_texture_lock()` seems to return a nullptr, so that could explain why the issue depends on the texture format. Maybe something goes wrong when creating the texture.

**Edit 2**: It looks like RGBA128 is reserved for compute shaders (see [here](https://github.com/armory3d/Kinc/blob/bac44a182515822dc900d5abadfd0297a68fe62a/Backends/Graphics4/Direct3D11/Sources/kinc/backend/graphics4/texture.cpp#L145-L149) and [here](https://github.com/armory3d/Kinc/blob/bac44a182515822dc900d5abadfd0297a68fe62a/Backends/Graphics4/Direct3D11/Sources/kinc/backend/graphics4/texture.cpp#L160-L166)) and the CPU is not able to write to the data. I wonder how floats should be written into textures then if the minimum floating point size is 32 bit (`kha.FastFloat`)? Still, Krom/Armorcore shouldn't crash probably?

**Comment by luboslenco** [comment]
Hey, thanks for report. Yes, it's the issue of the kinc / d3d11 backend, it should not be hard-coded like that. As a workaround [kha.Image.fromBytes()](https://github.com/armory3d/armory/blob/master/Sources/armory/data/ConstData.hx#L14) will work, but the kinc issue should still get resolved eventually to prevent the crash.

**Comment by MoritzBrueckner** [comment]
Thanks! However I'm not sure if `Image.fromBytes` is implemented on targets like Android, but let's see. At least it works on Krom now :)
