### ISSUE TITLE
Build Fail: missing architecture required by this target: arm64

### ISSUE THREAD

**Issue by uwe22** [armory3d/armorcore#18]
Many thanks for your hard work.
I tried to compile armorcore on bigsur 11.2.3 on mac mini apple silicon with M1.

I followed your instructions . 

the first part executes well:

`armorcore % node Kinc/make -g metal
Using Kinc (bac44a18) from /Users/alarix/Documents/development/armorcore/Kinc
kincfile found.
Creating macOS project files.
Compiling shader 1 of 10 (g1.frag).
Compiling shader 2 of 10 (g1.vert).
Compiling shader 3 of 10 (painter-colored.frag).
Compiling shader 4 of 10 (painter-colored.vert).
Compiling shader 5 of 10 (painter-image.frag).
Compiling shader 6 of 10 (painter-image.vert).
Compiling shader 7 of 10 (painter-text.frag).
Compiling shader 8 of 10 (painter-text.vert).
Compiling shader 9 of 10 (painter-video.frag).
Compiling shader 10 of 10 (painter-video.vert).
`

but build with Xcode fails: 

![Screen Shot 2021-03-20 at 1 17 25](https://user-images.githubusercontent.com/11908297/111811093-0ae70780-891a-11eb-8388-d533eff881a6.jpg)

I am thankful for any help.

**Comment by luboslenco** [comment]
Sorry no apple sillion support yet (https://github.com/armory3d/armorcore/actions/runs/611413734) :(. Will fix asap once I get a hold of the hardware, in the upcoming months.
