### ISSUE TITLE
Failing to compile with --debug on Linux / Debug on Linux?

### ISSUE THREAD

**Issue by N8n5h** [armory3d/armorcore#21]
I'm trying to debug this https://github.com/armory3d/armory/issues/2158, so I thought that maybe by compiling with `--debug` I could get a stack trace or something other than the exception. 

But when I try to run `node Kinc/make -g opengl --debug --compiler clang --compile` it results in a compilation fail with: `/usr/bin/ld: cannot find -lv8_monolith`.

**Comment by luboslenco** [comment]
There is no debug v8 library compiled for Linux  yet, sorry. The v8 library is added here:
https://github.com/armory3d/armorcore/blob/master/kincfile.js#L83

Maybe it will be enough to link the release one, by changing it to `project.addLib('v8_monolith -L../../release');` and adding [these defines](https://github.com/armory3d/armorcore/blob/master/kincfile.js#L78). I will look into adding debug v8 lib for Linux on the next update as a proper fix. In the meantime the [Kode/Krom](https://github.com/Kode/Krom) should still work for Armory.

**Comment by N8n5h** [comment]
> Maybe it will be enough to link the release one, by changing it to project.addLib('v8_monolith -L../../release'); and adding these defines. I will look into adding debug v8 lib for Linux on the next update as a proper fix. 

Tested it but it still just shows the same untraceable error :pensive: 

> In the meantime the Kode/Krom should still work for Armory.

I will try this but I think the issue may be armorcore specific? Because of that `v8::ToLocalChecked`...

Any other alternative for debugging on linux?
