### ISSUE TITLE
Zui text not rendering on Linux

### ISSUE THREAD

**Issue by N8n5h** [armory3d/armorcore#23]
Screenshot of Krom from kromx_bin/master

![Text working](https://user-images.githubusercontent.com/42382648/115130181-b5a72000-9fc3-11eb-8cde-f052cdc36aec.png)

Screenshot of replaced manual build from latest commit:

![Screenshot from 2021-04-17 21:26:48](https://user-images.githubusercontent.com/42382648/115130201-e6875500-9fc3-11eb-953d-8e47d180a38f.png)

Is it something wrong on my end that I missed when compiling?

### Steps

I followed the steps to compile from the `README.md`.

Replaced the file to a copy of the armory sdk from latest commit.

New file on blender -> Enable debug console -> Play.

### System
OS: Ubuntu 20.04.2 LTS

**Comment by luboslenco** [comment]
I did some testing and I do not think anything is wrong on your end. There may have been some changes in Kinc, causing this issue when used with current https://github.com/armory3d/Kha. However, I recall that in latest Kha `lockInt16()` functionality is not yet finished - details at https://github.com/armory3d/iron/issues/119#issuecomment-806588577, so it's not possible to update https://github.com/armory3d/Kha yet.

I will do my best to switch armory to armorcore soon so there is less exposure to all these dependencies.

**Comment by N8n5h** [comment]
Cool, thanks for confirming and the info! :smile:

**Comment by N8n5h** [comment]
@luboslenco, sorry to bother you, but this issue is still present after https://github.com/armory3d/Kromx_bin/commit/e6328536db565a5a30a65233192c78f6de6466d0

**Comment by MoritzBrueckner** [comment]
Seems to be working again after todays SDK update, at least on Windows where it was also broken yesterday.

**Comment by N8n5h** [comment]
> Seems to be working again after todays SDK update, at least on Windows where it was also broken yesterday.

Yep, could confirm that is working on Linux too! :partying_face:
