### ISSUE TITLE
Improve sysCommand implementation on Windows

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorcore#25]
Hey,
internally the sysCommand function on Windows is implemented in terms of _wsystem. This has the drawback of opening and closing a console window for every call. Especially for the cloud library this opens and closes lots of terminal windows. May I improve the implementation such that it does not _wsystem anymore but the recommended CreateProcess function on Windows to avoid the terminal window issue?
Warning: The code will be a bit longer than it currently is.

**Comment by luboslenco** [comment]
That would be welcome, thanks! The cloud library will switch to using `Krom.httpRequest` but it would be still nice to have `Krom.sysCommand` not open the console window. 🙂
