### ISSUE TITLE
Improving sysCommand even further

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorcore#26]
Sorry for asking again but I studied the code in more detail and realized that most uses of sysCommand are somehow unnecessary or better to be implemented without system.
That's why I wanted to ask whether I could reduce usage of sysCommand by implementing them directly 
i.e. createDirectory by some new function krom_create_directory
delete by some new function krom_delete_file  and so on
I think it would be a good style to avoid system as much as possible. Of course I will improve the sysCommand none the less.
What do you think?

**Comment by luboslenco** [comment]
Yup that would be awesome!🙂
