### ISSUE TITLE
haxe.Exception is printed as "Uncaught [object Object]"

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorcore#32]
Add a [`haxe.Exception`](https://api.haxe.org/haxe/Exception.html) anywhere in the code, like this:

```haxe
throw new haxe.Exception("test");
```

and Armorcore will output `Trace: Uncaught [object Object]` instead of showing the actual exception. Tested on Windows, using Krom.exe from armory3d/Kromx_bin at [`https://github.com/armory3d/armorcore/commit/4795862a96832378e370e999c379672843eaf37d`](https://github.com/armory3d/armorcore/commit/4795862a96832378e370e999c379672843eaf37d).

**Comment by MoritzBrueckner** [comment]
I found a solution, but I'm not sure how good it is as I don't have any prior experience with V8.

```c++
void handle_exception(TryCatch *try_catch) {
	MaybeLocal<Value> trace = try_catch->StackTrace(isolate->GetCurrentContext());
	if (trace.IsEmpty()) {
		// The 3 lines below this comment were changed, try_catch->Exception()
		// is used instead of try_catch->Message()
		v8::Local<v8::Value> exception = try_catch->Exception();
		String::Utf8Value exception_str(isolate, exception);
		write_stack_trace(*exception_str);
	}
	else {
		String::Utf8Value stack_trace(isolate, trace.ToLocalChecked());
		write_stack_trace(*stack_trace);
	}
}
```

I'm not sure why the message of Haxe exceptions somehow seems to be an object of unknown type (?), but this way it seems to work. Are there any cases where this doesn't work and where `try_catch->Message()` should be used instead?

**Comment by luboslenco** [comment]
> Are there any cases where this doesn't work and where try_catch->Message() should be used instead?

Hm not sure.. I was wondering why it is working ok in ArmorPaint, it turns out all is well when

`project.addDefine("js-es=6");`

is set. Not sure why it is not enabled by default, if there are no issues we could make it so in Armory.

https://haxe.org/manual/target-javascript-es6.html

**Comment by MoritzBrueckner** [comment]
With ES6 enabled Haxe exceptions are indeed printed correctly and I think we can enable it for Armory. If Armorcore supports it then there are no further platform limitations, right? Are there any cases where it shouldn't be enabled?

**Comment by luboslenco** [comment]
That should be correct! Not aware of any cases.
