### ISSUE TITLE
VSCode: debugger doesn't attach to Armorcore process on Windows

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorcore#36]
When selecting the Armorcore binaries from Kromx_bin for the Krom path in VSCode, the debugger isn't able to pause the process, set breakpoints and most importantly there is no console output, so trace statements and exceptions can't be seen. A while ago this was not the case I think, so I suspect it is caused by some newer changes. Or do Armorcore and V8 need to be compiled in debug mode?

I'm using the latest VSCodium on Windows 10 with the current Armorcore binaries from SDK/Krom and the latest Kha version. Someone else on the Armory Discord also has this issue, and there currently is no way to debug Krom projects because Kode/Krom doesn't even start (that's another issue though :)).

**Edit**: when using Armory's Kha version, Armorcore instantly crashes and generates an empty kinc.dmp file.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armorcore/issues/54.
