### ISSUE TITLE
Audio sample rate issues

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorcore#37]
Hi,

first of all, this is more of a question than a bug report.

Currently, the sample rate in the Haxe audio code for the Armorcore backend is [hard-coded](https://github.com/armory3d/Kha/blob/aee26765344bcf6024375d58101a2f892a3d954b/Backends/Krom/kha/audio2/Audio.hx#L13-L14) which can lead to wrong playback depending on the audio device. On HL, the same issue was quite straightforward to [fix](https://github.com/Kode/Kha/pull/1383), but on Krom I don't know of any currently existing way to retrieve the application sample rate via Haxe.

I am willing to fix this but before proceeding, I want to ask if something like `Krom.getSampleRate()` would be a good solution or if it is possible and a good idea to directly expose variables in some other way? All I need to do is to access `kinc_a2_samples_per_second` from Haxe.

Because I would also need to change armory3d/Kha to fix this issue: are there some patch files somewhere so that the changes can be semi-automated for updates of Kha from the Kode organization?

Also, do you know if a sound's sample rate (which is also hard-coded currently) is definitely always 44100Hz after loading? `Krom.loadSound()` just returns the raw samples data, discarding any other attribute of the created `kinc_a1_sound_t` struct. The currently unset length can be reverse-engineered by using `length = count / 2 / sampleRate` in the [sound's constructor](https://github.com/armory3d/Kha/blob/aee26765344bcf6024375d58101a2f892a3d954b/Backends/Krom/kha/krom/Sound.hx#L6), but there might be other attributes that are worth accessing from Haxe. I wonder how a solution for that could look like?

The reason why I'm doing this for the Armory repos and not for the Kode counterpart is that I don't think that audio on Kode/Krom will be fixed/implemented any time soon, so I can't really test my fix there.

**Comment by MoritzBrueckner** [comment]
Hi, since this issue came up again on Discord today: I would be happy to provide a fix, but in order to do this there needs to be some way to add persistent changes to the armory3d/Kha repo without them being overwritten the next time armory3d/Kha is updated from Kode/Kha. 

Kode/Krom currently doesn't support audio, so Robert probably wouldn't accept any untested Krom-related audio changes until he has reimplemented audio (if that every happens).

**Comment by luboslenco** [comment]
Sorry this took so long, if someone still gets to this then `Krom.getSampleRate()` sounds ok, and we can create some patch for `armory3d/Kha`. It's not ideal but the `armory3d/Kha` already contains some armory fixes anyway.

> Also, do you know if a sound's sample rate (which is also hard-coded currently) is definitely always 44100Hz after loading?

Hm not sure about this.
