### ISSUE TITLE
Missing glsl_to_spirv library

### ISSUE THREAD

**Issue by tong** [armory3d/armorcore#38]
It seems the repository is missing the [armory3d/glsl_to_spirv](https://github.com/armory3d/glsl_to_spirv) library.
Without, building linux/vulkan fails with:
```sh
Error: ENOENT: no such file or directory, open '… /armorcore/Libraries/glsl_to_spirv/kincfile.js'
```

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armorcore/commit/f732bf43a7c251a4cb526ac55928a4475038756b.
