### ISSUE TITLE
Socket support

### ISSUE THREAD

**Issue by tong** [armory3d/armorcore#39]
This https://github.com/tong/armorcore/compare/master...socket-hack adds support for tcp/udp sockets but only for linux since https://github.com/Kode/Kinc/issues/672

**Comment by tong** [comment]
[wip]
Here is a new branch using a modified version of the kinc implementation:
https://github.com/tong/armorcore/tree/socket-support
https://github.com/tong/Kinc/tree/socket-api-fix

It's a bit of a rabbit hole to decide what parts of the api should be exposed and what not. It would be nice to be complete as possible, but then we have to deal with a monster hard to tame on non posix systems.

The python api gives a good overview about the scope: https://docs.python.org/3/library/socket.html

**Comment by tong** [comment]
Example usage in armory:
https://github.com/tong/armory_examples/tree/net_socket-example/net_socket
... includes a kinc based echo server for testing in the server/ directory (also utilizing the changed socket api).

**Comment by luboslenco** [comment]
Happy to take it in! Please just add some `WITH_SOCKETS` define surrounding it.

**Comment by tong** [comment]
Accidentally closed the issue?

There were some changes made to the kinc socket implementation which might have broken my implementation in armorcore.
