### ISSUE TITLE
macos build hangs

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorcore#44]
Hi,

first of all, I'm not the one experiencing this issue since I'm not a MacOS user. However many other people seem to experience the error `Could not load krom.js, aborting` for all their Armory projects when targeting Krom, and since it is usually reported in other places I want to let you know about this.

Reports of this issue:
- https://forums.armory3d.org/t/krom-wont-work-macos/4833
- https://forums.armory3d.org/t/having-issues-problems-running-krom-in-mac-os/4856
- https://github.com/armory3d/armory/issues/2486#issuecomment-1186036444
- https://forums.armory3d.org/t/not-possible-to-start-in-browser-or-krom-on-macosx/4991

On the Discord server there is a report of this issue that dates back to 09/2020, so maybe it already exists since then. Not many people use Armory on MacOS, so it might be possible.

**Comment by luboslenco** [comment]
I have pushed https://github.com/armory3d/armorcore/commit/cdeba7945713e90efb104751917eb81e5d873bd4 which gets rid of the `Could not load krom.js, aborting` error but it still hangs, need to investigate more.

**Comment by voidref** [comment]
I found the bug and have a fix, will open a PR soon.

**Comment by voidref** [comment]
Ok, the PR would have been rather awkward having to be against some other diff, so here's a diff of the one line fix

```
diff --git a/Sources/kinc/io/filereader.h b/Sources/kinc/io/filereader.h
index 428492b..0e86e2d 100644
--- a/Sources/kinc/io/filereader.h
+++ b/Sources/kinc/io/filereader.h
@@ -245,7 +245,7 @@ void kinc_internal_uwp_installed_location_path(char *path);
 #ifndef KORE_ANDROID
 bool kinc_file_reader_open(kinc_file_reader_t *reader, const char *filename, int type) {
        memset(reader, 0, sizeof(kinc_file_reader_t));
-       char filepath[1001];
+    char filepath[1001] = { NULL };
 #ifdef KORE_IOS
        strcpy(filepath, type == KINC_FILE_TYPE_SAVE ? kinc_internal_save_path() : iphonegetresourcepath());
        if (type != KINC_FILE_TYPE_SAVE) {
```

The issue was that some compilers in C do not initialize stack arrays to nil, and there was a nil termination error when appending and copying to the filepath buffer.

**Comment by voidref** [comment]
PS: Not sure why the indentation is different? sorry about that.

**Comment by luboslenco** [comment]
Hopefully all good now with the latest https://github.com/Kode/Kinc/blob/main/Sources/kinc/io/filereader.h, thanks for the additional info.
