### ISSUE TITLE
Crash when printing error message about invalid cast

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorcore#45]
Example Armory project (press F5 -> instant crash):
[KromCrashCast.zip](https://github.com/armory3d/armorcore/files/9159633/KromCrashCast.zip)

When a safe cast fails, Armorcore crashes when printing the error message:

```haxe
cast(iron.Scene.active.root, iron.object.MeshObject);
```

In the example project above, the reported call stack differs a bit from the project where I found this issue, but I think in both cases it's the same problem.

**Call Stack (example project)**:
```
>	Armory.exe!__report_gsfailure(unsigned __int64 stack_cookie) Line 220	C
 	Armory.exe!kinc_log_args(kinc_log_level_t level, const char * format, char * args) Line 134	C
 	Armory.exe!kinc_log(kinc_log_level_t level, const char * format, ...) Line 88	C
 	Armory.exe!`anonymous namespace'::write_stack_trace(const char * stack_trace) Line 254	C++
 	[Inline Frame] Armory.exe!?A0xf48f1acd::handle_exception(v8::TryCatch *) Line 277	C++
 	Armory.exe!`anonymous namespace'::run_v8() Line 3681	C++
 	Armory.exe!`anonymous namespace'::update() Line 3770	C++
 	[Inline Frame] Armory.exe!kinc_internal_update_callback() Line 374	C
 	[Inline Frame] Armory.exe!kinc_internal_frame() Line 477	C
 	Armory.exe!kinc_start() Line 492	C
 	Armory.exe!kickstart(int argc, char * * argv) Line 4496	C++
 	Armory.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 1307	C
 	[External Code]	
```

**Console output (example project)**:
```
					...
					renderPathTime : <...>, 
					frameTimeAvgMax : <...>, 
					frameTimeAvgMin : <...>, 
					frameTimeAvg : <...>, 
					frames : <...>, 
					totalT៛잻ⴷ
Unhandled exception at 0x00007FF72AD52F69 in Armory.exe: Stack cookie instrumentation code detected a stack-based buffer overrun.

The program '[41444] Armory.exe' has exited with code 0 (0x0).
```

You can see that it prints the object that could not be casted (I've only shown the end of the print before it fails), and somehow the attribute `totalTime` of the DebugConsole trait cannot be displayed anymore. The wrong characters are different for each run (so probably garbage memory) and I think it's because the error message is too long/long error messages aren't correctly handled. Adding a string conversion method to `iron.Object` to produce shorter outputs wouldn't be a bad idea either I think :)

**Call stack (original project)**:

In the original project, the error doesn't happen on init but after a keyboard interaction, so I think that's why the call stack is a bit different:

```
>	Armory.exe!stbsp_vsprintfcb(char *(*)(const char *, void *, int) buf, void * fmt, char * va, const char *) Line 1258	C
 	[Inline Frame] Armory.exe!stbsp_vsprintf(char *) Line 1474	C
 	[Inline Frame] Armory.exe!kinc_microsoft_format(const char *) Line 45	C
 	Armory.exe!kinc_log_args(kinc_log_level_t level, const char * format, char * args) Line 96	C
 	[External Code]	
```

**End of console output (original project)**:

```
		rot : 0, 0, 0, 1, 
		scale : (1, 1, 1, 1), 
		dim : (2, 2, 2, 1), 
		radius : 3.4641016151377544, 
		dirty : false
	}
}
Exception thrown: write access violation.
**bf** was 0xED5D930000.
```

Here it seems that the full message can be printed, but it still crashes. Let me know if you need a better example that exactly reproduces the second callback/error.

**Used Armorcore**:
Latest master (cdeba7945713e90efb104751917eb81e5d873bd4), using VS 2022 on Windows in release mode for x64.

**Comment by luboslenco** [comment]
Sorry I do not know when I get to fix this, however if someone gets to it then PR is welcome.
