### ISSUE TITLE
Getting rid of unused_result warnings

### ISSUE THREAD

**Issue by tong** [armory3d/armorcore#48]
There are a lot of compiler warnings like: `warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]`
Most of them are caused by setting a field on the return value object where we ignore the result of the function anyhow.

```cpp
obj->Set(isolate->GetCurrentContext(), ... 
```
We can define `Wno-unused-result` but might lose vital information somewhere else.
So how about changing to:
```cpp
Maybe<bool> r = obj->Set(isolate->GetCurrentContext(), ... 
```
or by casting to void:
```cpp
(void) obj->Set(...
```
@luboslenco I can make this change if that's ok for you.

**Comment by luboslenco** [comment]
> or by casting to void:

Sounds good!
