### ISSUE TITLE
V8 inspector protocol integration

### ISSUE THREAD

**Issue by tong** [armory3d/armorcore#54]
It would be nice to provide debug builds of the libv8 binaries to be able to debug armorcore using the [inspector protocol](https://chromedevtools.github.io/devtools-protocol/v8/) and [chrome devtools](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27).

- [Debugging over the V8 Inspector Protocol](https://v8.dev/docs/inspector)
- https://source.chromium.org/chromium/chromium/src/+/main:v8/test/inspector/

**Comment by MoritzBrueckner** [comment]
Do you know whether integrating the inspector protocol would also fix https://github.com/armory3d/armorcore/issues/36?

**Comment by tong** [comment]
Yes, i think so, since armorcore had to be compiled with (v8) debug support and expose the api to talk with it.

**Comment by luboslenco** [comment]
Debug builds are available via https://github.com/luboslenco/v8_builder, but too big to be included directly in https://github.com/armory3d/v8_bin. Not sure if I get to implement it myself, sorry.
