### ISSUE TITLE
Windows opengl build and workflow artifact storage

### ISSUE THREAD

**Issue by tong** [armory3d/armorcore#57]
Since it's not possible to compile dx11, dx12 shaders on linux it would be nice to have armsdk distributed including a windows-opengl binary (armory3d/armory#2164, armory3d/armory#1305).

As i don't have a windows machine around i've configured a workflow to build the binary and store it as artifact for download: https://github.com/tong/armorcore/blob/add-windows-opengl-workflow/.github/workflows/windows_opengl.yml

@luboslenco Do you want to include this in the repo, and if so should i configure the workflow storage for the other targets too?

**Comment by luboslenco** [comment]
Hm sorry would like to get rid of opengl eventually. Maybe we can start experimenting with vulkan builds for this purpose? Needs more work in Kinc but perhaps it could already work for a minimal render path and we can continue to fix what's not working yet.
