### ISSUE TITLE
Memory leak in Krom (armorcore) when using webworkers

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armorcore#58]
Initializing a simple worker thread causes memory leak on Windows (not tested on other platforms).

Haxe worker initialization:
```Haxe
var worker = new js.html.Worker('testscript.js');
```

`testscript.js`:
```JS
onmessage = function(message){
    let x = 10;
}
```

Even if the script is basically empty, simply initializing a worker thread causes memory leak issues. No warming or errors during the compile and run. Memory consumed by armorcore runtime continuously increases.

**Comment by MoritzBrueckner** [comment]
The leaked memory is allocated here:
https://github.com/armory3d/armorcore/blob/2c6b8b3a2104f2f1406d3f44bc808de06dda5aca/Sources/worker.cpp#L93-L94

Call stack:
```
kernel32.dll!0x7fff70a77614()
Armory.exe!heap_alloc_dbg_internal() - Line 359
Armory.exe!heap_alloc_dbg() - Line 450
Armory.exe!_malloc_dbg() - Line 496
Armory.exe!malloc() - Line 27
Armory.exe!operator new() - Line 35
Armory.exe!operator new() - Line 30
Armory.exe!operator new[]() - Line 29
Armory.exe!v8::internal::HandleScope::Extend(class v8::internal::Isolate *)() - Line 0
Armory.exe!v8::internal::HandleScope::CreateHandle(class v8::internal::Isolate *,unsigned __int64)() - Line 0
Armory.exe!v8::Local<v8::Context>::New() - Line 322
Armory.exe!v8::Local<v8::Context>::New() - Line 266
Armory.exe!`anonymous namespace'::handle_message_queue() - Line 95
Armory.exe!`anonymous namespace'::worker_thread_func() - Line 302
Armory.exe!ThreadProc() - Line 19
```

Each call of [`handle_message_queue()`](https://github.com/armory3d/armorcore/blob/2c6b8b3a2104f2f1406d3f44bc808de06dda5aca/Sources/worker.cpp#L88) allocates memory for the `Local<Context>` object, but it isn't freed afterwards.

I think I found a fix, but I'm not sure about it:

The [documentation on `Local<T>`](https://v8docs.nodesource.com/node-0.8/de/deb/classv8_1_1_local.html#details) says:
> A light-weight stack-allocated object handle. All operations that return objects from within [v8](https://v8docs.nodesource.com/node-0.8/d2/dc3/namespacev8.html) return them in local handles. They are created within HandleScopes, and all local handles allocated within a handle scope are destroyed when the handle scope is destroyed. Hence it is not necessary to explicitly deallocate local handles.

So as long as there is a [`HandleScope`](https://v8docs.nodesource.com/node-0.8/d3/d95/classv8_1_1_handle_scope.html), the memory should be automatically freed when V8 decides so. `handle_message_queue()` currently doesn't have a `HandleScope`, but the calling functions `worker_thread_func()` and `handle_worker_messages()` have. I'm not completely sure about what counts as "within the same scope", but I guess that a called function doesn't count and as such we need to add a `HandleScope` to `handle_message_queue()` as well:

```cpp
HandleScope scope(isolate); // This line is new
Local<Context> current_context = Local<Context>::New(isolate, context);
Context::Scope context_scope(current_context);
```

After adding this, the memory leak is gone, and I think this is the correct way. The `current_context` object is only used within that scope as far as I can see, so it should be safe. However, I'm pretty new to the V8 API so I can only really guess at the moment...

@QuantumCoderQC if you can build Armorcore, could you please test this change and tell me whether it works for you?
