### ISSUE TITLE
Error: Compile error strip: 'Krom': No such file

### ISSUE THREAD

**Issue by NicTanghe** [armory3d/armorcore#60]
```bash
❯ Kinc/make -g vulkan --compiler clang --compile
cd Deployment
strip Krom
Using Kinc (d7af3bbe) from /home/nanghe/git/armortools/armorcore/Kinc
kfile found.
Creating Linux project files.
Using Kha from /home/nanghe/git/armortools/armorcore
Neither Kha directory nor project file (khafile.js) found.
Compiling shader 1 of 2 (g1.frag).
Compiling shader 2 of 2 (g1.vert).
Compiling...
[1/3] clang -O2 -I../../v8/include -I../../Kinc/Sources -I../../Kinc/Backends/System/Linux/Sources -I../../Kinc/Backends/System/POSIX/Sources -I../wayland -I../../Kinc/Backends/Graphics5/Vulkan/Sources -I../../Kinc/Backends/Graphics4/G4onG5/Sources -DKINC_NO_WAYLAND -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LZ4X -DKORE_VULKAN -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 -DKORE_G4 -DKORE_G5 -DKORE_G4ONG5 -DNDEBUG -MD -MF waylandunit.o.d -c ../wayland/wayland-generated/waylandunit.c -o waylandunit.o
[2/3] clang++ -std=c++17 -O2 -I../../v8/include -I../../Kinc/Sources -I../../Kinc/Backends/System/Linux/Sources -I../../Kinc/Backends/System/POSIX/Sources -I../wayland -I../../Kinc/Backends/Graphics5/Vulkan/Sources -I../../Kinc/Backends/Graphics4/G4onG5/Sources -DKINC_NO_WAYLAND -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LZ4X -DKORE_VULKAN -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 -DKORE_G4 -DKORE_G5 -DKORE_G4ONG5 -DNDEBUG -MD -MF main.o.d -c ../../Sources/main.cpp -o main.o
FAILED: main.o
clang++ -std=c++17 -O2 -I../../v8/include -I../../Kinc/Sources -I../../Kinc/Backends/System/Linux/Sources -I../../Kinc/Backends/System/POSIX/Sources -I../wayland -I../../Kinc/Backends/Graphics5/Vulkan/Sources -I../../Kinc/Backends/Graphics4/G4onG5/Sources -DKINC_NO_WAYLAND -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LZ4X -DKORE_VULKAN -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 -DKORE_G4 -DKORE_G5 -DKORE_G4ONG5 -DNDEBUG -MD -MF main.o.d -c ../../Sources/main.cpp -o main.o
../../Sources/main.cpp:1473:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] image->data;
                        ^        ~~~~~~~~~~~
../../Sources/main.cpp:2002:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] content->Data();
                        ^        ~~~~~~~~~~~~~~~
../../Sources/main.cpp:2032:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] content->Data();
                        ^        ~~~~~~~~~~~~~~~
../../Sources/main.cpp:2099:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] image->data;
                        ^        ~~~~~~~~~~~
../../Sources/main.cpp:3277:3: error: no matching function for call to 'kinc_raytrace_acceleration_structure_init'
                kinc_raytrace_acceleration_structure_init(&accel, &commandList, vertex_buffer, index_buffer, scale);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../Kinc/Sources/kinc/graphics5/raytrace.h:37:16: note: candidate function not viable: requires 4 arguments, but 5 were provided
KINC_FUNC void kinc_raytrace_acceleration_structure_init(kinc_raytrace_acceleration_structure_t *accel, struct kinc_g5_command_list *command_list,
               ^
../../Sources/main.cpp:3322:3: error: use of undeclared identifier 'kinc_raytrace_set_textures'
                kinc_raytrace_set_textures(&texpaint0->impl._renderTarget, &texpaint1->impl._renderTarget, &texpaint2->impl._renderTarget, &texenv->impl._texture, &texsobol->impl._texture, &texscramble->impl._texture, &texrank->impl._texture);
                ^
../../Sources/main.cpp:3343:3: error: no matching function for call to 'kinc_raytrace_set_target'
                kinc_raytrace_set_target(&render_target->impl._renderTarget);
                ^~~~~~~~~~~~~~~~~~~~~~~~
../../Kinc/Sources/kinc/graphics5/raytrace.h:43:16: note: candidate function not viable: no known conversion from 'kinc_g5_render_target_t *' (aka 'kinc_g5_render_target *') to 'struct kinc_g5_texture *' for 1st argument
KINC_FUNC void kinc_raytrace_set_target(struct kinc_g5_texture *output);
               ^
4 warnings and 3 errors generated.
ninja: build stopped: subcommand failed.
Build time: 0m 0s
Compilation failed.
Error: Compile error
strip: 'Krom': No such file
```

**Comment by NicTanghe** [comment]
❯ Kinc/make -g vulkan --compiler clang --compile
cd Deployment
strip armorcore
Using Kinc (d7af3bbe) from /home/nanghe/git/armortools/armorcore/Kinc
kfile found.
Creating Linux project files.
Using Kha from /home/nanghe/git/armortools/armorcore
Neither Kha directory nor project file (khafile.js) found.
Compiling shader 1 of 2 (g1.frag).
Compiling shader 2 of 2 (g1.vert).
Compiling...
[1/3] clang -O2 -I../../v8/include -I../../Kinc/Sources -I../../Kinc/Backends/System/Linux/Sources -I../../Kinc/Backends/System/POSIX/Sources -I../wayland -I../../Kinc/Backends/Graphics5/Vulkan/Sources -I../../Kinc/Backends/Graphics4/G4onG5/Sources -DKINC_NO_WAYLAND -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LZ4X -DKORE_VULKAN -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 -DKORE_G4 -DKORE_G5 -DKORE_G4ONG5 -DNDEBUG -MD -MF waylandunit.o.d -c ../wayland/wayland-generated/waylandunit.c -o waylandunit.o
[2/3] clang++ -std=c++17 -O2 -I../../v8/include -I../../Kinc/Sources -I../../Kinc/Backends/System/Linux/Sources -I../../Kinc/Backends/System/POSIX/Sources -I../wayland -I../../Kinc/Backends/Graphics5/Vulkan/Sources -I../../Kinc/Backends/Graphics4/G4onG5/Sources -DKINC_NO_WAYLAND -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LZ4X -DKORE_VULKAN -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 -DKORE_G4 -DKORE_G5 -DKORE_G4ONG5 -DNDEBUG -MD -MF main.o.d -c ../../Sources/main.cpp -o main.o
FAILED: main.o
clang++ -std=c++17 -O2 -I../../v8/include -I../../Kinc/Sources -I../../Kinc/Backends/System/Linux/Sources -I../../Kinc/Backends/System/POSIX/Sources -I../wayland -I../../Kinc/Backends/Graphics5/Vulkan/Sources -I../../Kinc/Backends/Graphics4/G4onG5/Sources -DKINC_NO_WAYLAND -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LZ4X -DKORE_VULKAN -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 -DKORE_G4 -DKORE_G5 -DKORE_G4ONG5 -DNDEBUG -MD -MF main.o.d -c ../../Sources/main.cpp -o main.o
../../Sources/main.cpp:1473:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] image->data;
                        ^        ~~~~~~~~~~~
../../Sources/main.cpp:2002:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] content->Data();
                        ^        ~~~~~~~~~~~~~~~
../../Sources/main.cpp:2032:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] content->Data();
                        ^        ~~~~~~~~~~~~~~~
../../Sources/main.cpp:2099:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] image->data;
                        ^        ~~~~~~~~~~~
../../Sources/main.cpp:3277:3: error: no matching function for call to 'kinc_raytrace_acceleration_structure_init'
                kinc_raytrace_acceleration_structure_init(&accel, &commandList, vertex_buffer, index_buffer, scale);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../Kinc/Sources/kinc/graphics5/raytrace.h:37:16: note: candidate function not viable: requires 4 arguments, but 5 were provided
KINC_FUNC void kinc_raytrace_acceleration_structure_init(kinc_raytrace_acceleration_structure_t *accel, struct kinc_g5_command_list *command_list,
               ^
../../Sources/main.cpp:3322:3: error: use of undeclared identifier 'kinc_raytrace_set_textures'
                kinc_raytrace_set_textures(&texpaint0->impl._renderTarget, &texpaint1->impl._renderTarget, &texpaint2->impl._renderTarget, &texenv->impl._texture, &texsobol->impl._texture, &texscramble->impl._texture, &texrank->impl._texture);
                ^
../../Sources/main.cpp:3343:3: error: no matching function for call to 'kinc_raytrace_set_target'
                kinc_raytrace_set_target(&render_target->impl._renderTarget);
                ^~~~~~~~~~~~~~~~~~~~~~~~
../../Kinc/Sources/kinc/graphics5/raytrace.h:43:16: note: candidate function not viable: no known conversion from 'kinc_g5_render_target_t *' (aka 'kinc_g5_render_target *') to 'struct kinc_g5_texture *' for 1st argument
KINC_FUNC void kinc_raytrace_set_target(struct kinc_g5_texture *output);
               ^
4 warnings and 3 errors generated.
ninja: build stopped: subcommand failed.
Build time: 0m 0s
Compilation failed.
Error: Compile error
strip: 'armorcore': No such file

**Comment by luboslenco** [comment]
See https://github.com/armory3d/armortools/issues/1449 - vulkan raytracing patch still needs to be fixed.
