### ISSUE TITLE
Black screen since audio mixing was moved to C

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armorcore#63]
Hi, https://github.com/armory3d/armorcore/commit/e7e52a4b536f05f1f76c19edb358ad141dcf4d2c seems to have broken Armorcore when used together with Armory, this commit (up to the latest main) causes black screens in Armory because for some reason no draw command is sent to the GPU (in Renderdoc the list of draw events is empty). After closing the window the Krom process seems to continue in the background.

There are no error messages, and since no crash is taking place also no crash dumps. Before building the project, I modified the kfile to enable audio (`with_audio: true`) and workers (`with_worker: true`).

---

Not directly related to the black screen, but related to that commit:

It looks like you removed the possibility to register a custom audio callback (`kha.audio2.Audio.audioCallback`). I'm not sure whether this is actually _used_ anywhere in Kha (apart from providing it via the Kha API), but frameworks like https://github.com/MoritzBrueckner/aura will not work without the possibility to register a custom audio callback. Maybe there's a chance to bring this back in some way?

**Comment by luboslenco** [comment]
Restored audio mixing to previous / working state at https://github.com/armory3d/armorcore/tree/armsdk.
