### ISSUE TITLE
Armorlab / armorpaint on gumroad dont have alpha 1.0 available.

### ISSUE THREAD

**Issue by NicTanghe** [armory3d/armorcore#70]
Hello i bought armorlab . armorpaint.

I decided to update to 1.0 but the gumroad seems to have only been updated for armorpaint.

armorlab:
![image](https://github.com/armory3d/armorcore/assets/13624265/c0f28707-fa1e-4f73-8e82-7e1b84efbddd)

someone else`s armorpaint download tab looks like this :

![image](https://cdn.discordapp.com/attachments/486774102296625171/1171067412301492244/image0.jpg?ex=655b5484&is=6548df84&hm=b523e591838198cb62f4fbf56bbf9038aab63fe2a18c0bde103462ac810d3657&)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armortools/issues/1653.
