### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by e2002e** [armory3d/armorcore#71]
When compiling on ubuntu 23, I got:

`FAILED: main.o 
clang++ -std=c++17 -O2 -I../../v8/include -I../../Kinc/Sources -I../../Kinc/Backends/System/Linux/Sources -I../../Kinc/Backends/System/POSIX/Sources -I../../Kinc/Backends/Graphics5/Vulkan/Sources -I../../Kinc/Backends/Graphics4/G4onG5/Sources -DKINC_NO_WAYLAND -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LZ4X -DKORE_VULKAN -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 -DKORE_G4 -DKORE_G5 -DKORE_G4ONG5 -DNDEBUG -MD -MF main.o.d -c ../../Sources/main.cpp -o main.o
../../Sources/main.cpp:3699:3: error: no matching function for call to 'kinc_raytrace_acceleration_structure_init'
                kinc_raytrace_acceleration_structure_init(&accel, &commandList, vertex_buffer, index_buffer, scale);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../Kinc/Sources/kinc/graphics5/raytrace.h:37:16: note: candidate function not viable: requires 4 arguments, but 5 were provided
KINC_FUNC void kinc_raytrace_acceleration_structure_init(kinc_raytrace_acceleration_structure_t *accel, struct kinc_g5_command_list *command_list,
               ^
../../Sources/main.cpp:3802:3: error: use of undeclared identifier 'kinc_raytrace_set_textures'
                kinc_raytrace_set_textures(&texpaint0->impl._renderTarget, &texpaint1->impl._renderTarget, &texpaint2->impl._renderTarget, &texenv->impl._texture, &texsobol->impl._texture, &texscramble->impl._texture, &texrank->impl._texture);
                ^
../../Sources/main.cpp:3835:3: error: no matching function for call to 'kinc_raytrace_set_target'
                kinc_raytrace_set_target(&render_target->impl._renderTarget);
                ^~~~~~~~~~~~~~~~~~~~~~~~
../../Kinc/Sources/kinc/graphics5/raytrace.h:43:16: note: candidate function not viable: no known conversion from 'kinc_g5_render_target_t *' (aka 'kinc_g5_render_target *') to 'struct kinc_g5_texture *' for 1st argument
KINC_FUNC void kinc_raytrace_set_target(struct kinc_g5_texture *output);
`

**Comment by luboslenco** [comment]
Try using the `Kinc/make -g opengl --compiler clang --compile` command to compile with opengl, vulkan raytracing is wip.

**Comment by e2002e** [comment]
I was able to compile armorcore that way but it builds a program called "Armory", I just copied it under the name of Krom in the Krom folder of the sdk but I got this error when running a game.
Trace: TypeError: Krom.setAudioCallback is not a function
    at kha_SystemImpl.init (<anonymous>:34018:8)
    at kha_System.start (<anonymous>:33666:18)
    at start (<anonymous>:2823:15)
    at armory_system_Starter.main (<anonymous>:2847:3)
    at Main.main (<anonymous>:77:25)
    at <anonymous>:60986:6
    at <anonymous>:60987:3

**Comment by MoritzBrueckner** [comment]
@e2002e Support for custom audio callbacks (as used by Kha) was removed in https://github.com/armory3d/armorcore/commit/e7e52a4b536f05f1f76c19edb358ad141dcf4d2c, so you will need to compile older Armorcore versions for Armory at the moment. Also see https://github.com/armory3d/armorcore/issues/63.

**Comment by e2002e** [comment]
I can't compile it.
Using the commit just before e7e52a4, I got:
`FAILED: main.o 
clang++ -std=c++17 -O2 -I../../v8/include -I../../Kinc/Sources -I../../Kinc/Backends/System/Linux/Sources -I../../Kinc/Backends/System/POSIX/Sources -I../../Kinc/Backends/Graphics4/OpenGL/Sources -I../../Kinc/Backends/Graphics5/G5onG4/Sources -DKINC_NO_WAYLAND -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LZ4X -DKORE_OPENGL -DKINC_EGL -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 -DKORE_G4 -DKORE_G5 -DKORE_G5ONG4 -DNDEBUG -MD -MF main.o.d -c ../../Sources/main.cpp -o main.o
../../Sources/main.cpp:706:19: error: no matching function for call to 'kinc_g4_index_buffer_lock'
                int *vertices = kinc_g4_index_buffer_lock(buffer);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~
../../Kinc/Sources/kinc/graphics4/indexbuffer.h:52:17: note: candidate function not viable: requires 3 arguments, but 1 was provided
KINC_FUNC void *kinc_g4_index_buffer_lock(kinc_g4_index_buffer_t *buffer, int start, int count);
                ^
../../Sources/main.cpp:716:3: error: no matching function for call to 'kinc_g4_index_buffer_unlock'
                kinc_g4_index_buffer_unlock(buffer);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../../Kinc/Sources/kinc/graphics4/indexbuffer.h:65:16: note: candidate function not viable: requires 2 arguments, but 1 was provided
KINC_FUNC void kinc_g4_index_buffer_unlock(kinc_g4_index_buffer_t *buffer, int count);
               ^
../../Sources/main.cpp:1525:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] image->data;
                        ^        ~~~~~~~~~~~
../../Sources/main.cpp:2066:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] content->Data();
                        ^        ~~~~~~~~~~~~~~~
../../Sources/main.cpp:2096:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] content->Data();
                        ^        ~~~~~~~~~~~~~~~
../../Sources/main.cpp:2163:4: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
                        delete[] image->data;

I also checked out Kinc to about the same date. Same result.`

**Comment by MoritzBrueckner** [comment]
Maybe there was a version mismatch of Armorcore and Kinc at that point in the repo history, try applying https://github.com/armory3d/armorcore/commit/91203c36994a770de878aa234aec7f52f46aff1a which should at least fix the first few errors. For the other errors try to apply https://github.com/armory3d/armorcore/pull/64, or if that still doesn't fix everything navigate to the respective lines and try to replace the function that contains the lines with newer Armorcore code. It's messy, but it probably works.
