### ISSUE TITLE
[macOS] Kink: Metal buffer format mismatch

### ISSUE THREAD

**Issue by voidref** [armory3d/armorcore#75]
It looks like the default format doesn't match what Metal may return when it's set up.

```
-[MTLDebugRenderCommandEncoder setRenderPipelineState:]:1615: failed assertion `Set Render Pipeline State Validation
For color attachment 0, the render pipeline's pixelFormat (MTLPixelFormatBGRA8Unorm) does not match the framebuffer's pixelFormat (MTLPixelFormatRGBA16Float).
'
```

Honestly don't know enough about this stuff to suggest a solution, I may mess around with attempting to tell the metal buffer to use the format the engine prefers.

**Comment by voidref** [comment]
given this:

```/* This property controls the pixel format of the MTLTexture objects.
 * The two supported values are MTLPixelFormatBGRA8Unorm and
 * MTLPixelFormatBGRA8Unorm_sRGB. */

@property MTLPixelFormat pixelFormat;```

it looks like the frameBuffer will have to be wrangled into `MTLPixelFormatBGRA8Unorm`.

**Comment by voidref** [comment]
Ok, so I guess Kink is a 3rd party backend graphics rendering lib ... maybe it needs to be updated in this repo.

**Comment by luboslenco** [comment]
Will investigate together with issues at https://github.com/armory3d/armortools/issues/1671.
