### ISSUE TITLE
Compute shader not supported.

### ISSUE THREAD

**Issue by e2002e** [armory3d/armorcore#76]
Hi, we need support for computeShaders.
Is there a way to enable it when compiling ?

**Comment by luboslenco** [comment]
Hey, the compute functions need to be added here:
https://github.com/armory3d/armorcore/blob/armsdk/Sources/main.cpp#L2265

PR is welcome at https://github.com/armory3d/armorcore/tree/armsdk. There was an implementation in the past but I am not sure it worked correctly. Should be easy to re-add it though.

**Comment by e2002e** [comment]
I could do a pull request but it's on branch armsdk with the audio callback issue (fixed by reimplementing the old code).
I'd like to modify the main branch but there lack functions like createFragmentShader() and just copying and pasting the old code doesn't work here (would just crash).
