### ISSUE TITLE
Bug in minits

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorcore#80]
Out of curiosity I scrolled over your work in progress in `minits.js` code and found these lines in the `write_c` function

```
// Function declaration end
if (token == ")") {
	is_func_declaration = false;
}

// Skip function return type, as it's already written
if (is_func_declaration && token == ")" && next == ":") {
	stream.write(token);
	i++; // ":" token
	i++; // "i32" token
	continue;
}
```
which seems to be a bug as the second `if` is never executed. Moreover` ")"` could also appear in a `for_loop_header` which does not necessarily lead to a bug but is a bit shady nonetheless.

By the way your approach to convert Haxe to C via Typescript is very interesting to follow. I am already curious to see the next steps.

**Comment by luboslenco** [comment]
Thanks for the hint! Right now it's just a simple text processor but curious how it turns out as well. :) Will do some more work on it in the coming days.
