### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by majorsopa** [armory3d/armorcore#81]
Pulled the latest commit of this to try building on Windows and when attempting to compile I get the build error "C requires that a struct or union have at least one member".

The errors refer to lines 53-54 in `iron_array.h`:
```
typedef struct buffer {} buffer_t;
typedef struct buffer_view {} buffer_view_t;
```

**Comment by luboslenco** [comment]
Should be resolved, thanks for report.

(link https://github.com/armory3d/armortools/issues/1695)
